Please help out, this is too much for me to figure out,
am I on the wrong track?
I have the cwm cvs version.
here are my bugs :
1. cvs server: Diffing .
cvs server: failed to create lock directory for
`/sources/public/2000/10/swap'
(/sources/public/2000/10/swap/#cvs.lock): Permission denied
cvs server: failed to obtain dir lock in repository
`/sources/public/2000/10/swap'
cvs [server aborted]: read lock failed - giving up
2. given this file :
i have problems with cwm :
2.1 ~/cwm/cwm.py rewrite-ids.n3 --flatten
crashes
Traceback (most recent call last):
File "/home/mdupont/cwm/cwm.py", line 663, in ?
doCommand()
File "/home/mdupont/cwm/cwm.py", line 566, in doCommand
need(_store)
File "/home/mdupont/cwm/cwm.py", line 639, in need
_store.deleteFormula(workingContext) ##@@@@ very slow
AttributeError: RDFStore instance has no attribute 'deleteFormula'
2.2 ~/cwm/cwm.py rewrite-ids.n3 --ugly
produces no data
2.3 these options make invalid n3
~/cwm/cwm.py rewrite-ids.n3 --n3=sl | ~/cwm/cwm.py
notation3.BadSyntax: Line 39 of
file:/mnt/hda4/introspector_home/introspector/cvs/introspector-0.4/treecc/n3/ :
Bad syntax (']' expected) at ^ in:
( "treecc-" [
.run-1063437284.651636p21235#li8 rdf...
the expr. produced is
( "treecc-" [
.run-1063437342.906038p21252#li8 rdf:first
:file-uri-clean .
.run-1063437342.906038p21252#li8 rdf:rest [
.run-1063437342.906038p21252#li7 rdf:first
.run-1063437342.906038p21252#li7 rdf:rest [
rdf:first :namestr .
.run-1063437342.906038p21252#li6 rdf:rest
rdf:first "" .
rdf:rest rdf:nil ] ] ] ] )
2.3 /cwm/cwm.py rewrite-ids.n3 --n3=spartni | ~/cwm/cwm.py
This loses all the data, the only thing left is this :
@prefix :
http://introspector.sf.net/2003/08/16/introspector.owl# .
http://www.w3.org/2000/10/swap/log#forAll :file,
:file-uri,:file-uri-clean,:funky,:id, :linenumber,
:namestr,:type-uri, type-uri-clean, :typename .
http://www.w3.org/2000/10/swap/log#implies {:funky a :typename .
Please advise
thanks
mie
James Michael DuPont
Do you Yahoo!?
Yahoo! SiteBuilder - Free, easy-to-use web site design software
Thanks, the cvs is working now .
Here are more problems :
with file : http://introspector.sourceforge.net/2003/09/PythonAst.n3
mdupont File
"/mnt/hda4/development/development2/w3c/2000/10/swap/pretty.py", line
295, in _scan
mdupont if verbosity()  98: progress("scanning %s in context %s"
%(`x`, `context`),
mdupont RuntimeError: maximum recursion depth exceeded
mdupont the new cwm is going off the deep end!
Maybe you think this is strange?
Mike
James Michael DuPont
Do you Yahoo!?
Yahoo! SiteBuilder - Free, easy-to-use web site design software
Dear Semantic Web Developers,
I would like to know if you can acknowledge that these are bugs that I
have reported and if you can reproduce them?
has any one else reported them? Do you have a bug tracking database?
have you thought about making a rdf notation for the bug reports? that
is something I would find very interesting, it could be like the
testing software...but on the other side of the coin.
mike
James Michael DuPont
Do you Yahoo!?
Yahoo! SiteBuilder - Free, easy-to-use web site design software
